<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>basic</string>
	</array>
	<key>name</key>
	<string>HTBasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Line Comment</string>
			<key>match</key>
			<string>\!.+</string>
			<key>name</key>
			<string>comment.line.exclamation.basic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(-)?[0-9\.E]+\b</string>
			<key>name</key>
			<string>constant.numeric.basic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Paths</string>
			<key>match</key>
			<string>\/\w+\/</string>
			<key>name</key>
			<string>path.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+\$)\(|([A-Z]{2,})\(</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.basic</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>FUNCTION() or SUBFUNCTION$()</string>
			<key>end</key>
			<string>\)</string>
			<key>name</key>
			<string>meta.group</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>support.parameter.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>comment</key>
			<string>KEYWORD</string>
			<key>match</key>
			<string>\b[A-Z]{2,}\b</string>
			<key>name</key>
			<string>keyword.control.basic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Variables</string>
			<key>match</key>
			<string>\w+(\$)?</string>
			<key>name</key>
			<string>variable.other.readwrite.basic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>comment</key>
			<string>Quoted String</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>quoted.double.basic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>.</string>
					<key>name</key>
					<string>string.other.basic</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.basic</string>
	<key>uuid</key>
	<string>7579be69-ab90-44dc-bb18-45420320f1b3</string>
</dict>
</plist>
